server:
  port: 8080
spring:
  profiles:
    active: dev
# jwt配置
jwt:
  # 签发人
  issuer: vker
  # 秘钥
  secret: GhYbItmHEW+V3Khfw5pikrczNoYYGYrZMivr5klT9k4hmFgmHVNddk1k3agTB4XZYY8mM/XcNeiStl27LuHuVQ==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer
# mybatis配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto